### ISSUE TITLE
Searching for subreddits

### ISSUE THREAD

**Issue by Leskevicius** [mattbdean/JRAW#212]
How would one now search for subreddits?

i.e., RedditClient.searchSubreddits(string, allowNSFW); function

**Comment by mattbdean** [comment]
Just added this functionality. `searchSubreddits` returns a Paginator builder:

```kt
SubredditSearchPaginator.Builder builder = redditClient.searchSubreddits("<query>")
SubredditSearchPaginator p = builder
        .query("foo")
        .limit(yourLimit)
        .sorting(SubredditSearchPaginator.<whatever>)
        .build()
```

If you don't want to wait until v1.1.0, you can use JitPack:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.mattbdean:JRAW:7603b89'
}
```

**Comment by Leskevicius** [comment]
Thanks for resolving this for me so quickly.

I chose to use your api for the final project for Udacity Android Nanodegree.

Thanks for setting it up 👍

**Comment by Leskevicius** [comment]
Hey so I am using the 7603b89 version of the api.

I have this code as my login

```java
          UserAgent userAgent = new UserAgent(
                    context.getString(R.string.bot_platform),
                    context.getString(R.string.bot_appId),
                    context.getString(R.string.bot_version),
                    context.getString(R.string.bot_reddit_username));

            Credentials credentials = Credentials.script(
                    context.getString(R.string.bot_reddit_username),
                    context.getString(R.string.bot_reddit_password),
                    context.getString(R.string.client_id),
                    context.getString(R.string.client_secret)
            );

            NetworkAdapter adapter = new OkHttpNetworkAdapter(userAgent);
            RedditClient reddit = OAuthHelper.automatic(adapter, credentials);
```

and I get this exception:
```
FATAL EXCEPTION: AsyncTask #1 Process: com.magicbuddha.redditorsdigest, PID: 4339
           java.lang.RuntimeException: An error occurred while executing doInBackground()
               at android.os.AsyncTask$3.done(AsyncTask.java:325)
               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
               at java.lang.Thread.run(Thread.java:761)
            Caused by: java.lang.NullPointerException: Null accessToken
               at net.dean.jraw.models.internal.$AutoValue_OAuthDataJson.<init>($AutoValue_OAuthDataJson.java:22)
               at net.dean.jraw.models.internal.AutoValue_OAuthDataJson.<init>(AutoValue_OAuthDataJson.java:15)
               at net.dean.jraw.models.internal.AutoValue_OAuthDataJson$MoshiJsonAdapter.fromJson(AutoValue_OAuthDataJson.java:64)
                at net.dean.jraw.models.internal.AutoValue_OAuthDataJson$MoshiJsonAdapter.fromJson(AutoValue_OAuthDataJson.java:18)
                at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
                at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
                at net.dean.jraw.http.HttpResponse.deserializeWith(HttpResponse.kt:49)
                at net.dean.jraw.oauth.OAuthHelper.scriptOAuthData$lib(OAuthHelper.kt:97)
                at net.dean.jraw.oauth.OAuthHelper.automatic(OAuthHelper.kt:33)
                at net.dean.jraw.oauth.OAuthHelper.automatic$default(OAuthHelper.kt:28)
                at net.dean.jraw.oauth.OAuthHelper.automatic(OAuthHelper.kt)
                at com.magicbuddha.redditorsdigest.reddit.AuthenticateBotTask.doInBackground(AuthenticateBotTask.java:56)
                at com.magicbuddha.redditorsdigest.reddit.AuthenticateBotTask.doInBackground(AuthenticateBotTask.java:23)
                at android.os.AsyncTask$2.call(AsyncTask.java:305)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                at java.lang.Thread.run(Thread.java:761) 
```

**Comment by mattbdean** [comment]
Would you mind making a new issue? This seems unrelated.

**Comment by Leskevicius** [comment]
sure thing.
