### ISSUE TITLE
Authentication on build 7603b89 fails. Caused by: java.lang.NullPointerException: Null accessToken

### ISSUE THREAD

**Issue by Leskevicius** [mattbdean/JRAW#215]
Hey so I am using the 7603b89 version of the api.

I have this code as my login

          UserAgent userAgent = new UserAgent(
                    context.getString(R.string.bot_platform),
                    context.getString(R.string.bot_appId),
                    context.getString(R.string.bot_version),
                    context.getString(R.string.bot_reddit_username));

            Credentials credentials = Credentials.script(
                    context.getString(R.string.bot_reddit_username),
                    context.getString(R.string.bot_reddit_password),
                    context.getString(R.string.client_id),
                    context.getString(R.string.client_secret)
            );

            NetworkAdapter adapter = new OkHttpNetworkAdapter(userAgent);
            RedditClient reddit = OAuthHelper.automatic(adapter, credentials);
and I get this exception:

FATAL EXCEPTION: AsyncTask #1 Process: com.magicbuddha.redditorsdigest, PID: 4339
           java.lang.RuntimeException: An error occurred while executing doInBackground()
               at android.os.AsyncTask$3.done(AsyncTask.java:325)
               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
               at java.lang.Thread.run(Thread.java:761)
            Caused by: java.lang.NullPointerException: Null accessToken
               at net.dean.jraw.models.internal.$AutoValue_OAuthDataJson.<init>($AutoValue_OAuthDataJson.java:22)
               at net.dean.jraw.models.internal.AutoValue_OAuthDataJson.<init>(AutoValue_OAuthDataJson.java:15)
               at net.dean.jraw.models.internal.AutoValue_OAuthDataJson$MoshiJsonAdapter.fromJson(AutoValue_OAuthDataJson.java:64)
                at net.dean.jraw.models.internal.AutoValue_OAuthDataJson$MoshiJsonAdapter.fromJson(AutoValue_OAuthDataJson.java:18)
                at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
                at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
                at net.dean.jraw.http.HttpResponse.deserializeWith(HttpResponse.kt:49)
                at net.dean.jraw.oauth.OAuthHelper.scriptOAuthData$lib(OAuthHelper.kt:97)
                at net.dean.jraw.oauth.OAuthHelper.automatic(OAuthHelper.kt:33)
                at net.dean.jraw.oauth.OAuthHelper.automatic$default(OAuthHelper.kt:28)
                at net.dean.jraw.oauth.OAuthHelper.automatic(OAuthHelper.kt)
                at com.magicbuddha.redditorsdigest.reddit.AuthenticateBotTask.doInBackground(AuthenticateBotTask.java:56)
                at com.magicbuddha.redditorsdigest.reddit.AuthenticateBotTask.doInBackground(AuthenticateBotTask.java:23)
                at android.os.AsyncTask$2.call(AsyncTask.java:305)
                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                at java.lang.Thread.run(Thread.java:761)

**Comment by mattbdean** [comment]
I can't reproduce. Here's my code:

```java
public class Main2Activity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

        new Task().execute();
    }

    private static class Task extends AsyncTask<Void, Void, Void> {
        @Override
        protected Void doInBackground(Void... voids) {
            UserAgent userAgent = new UserAgent("<whatever>");
            Credentials credentials = Credentials.script(
                    "<username>",
                    "<password>",
                    "<client ID>",
                    "<client secret>"
            );

            NetworkAdapter adapter = new OkHttpNetworkAdapter(userAgent);
            RedditClient reddit = OAuthHelper.automatic(adapter, credentials);
            Log.i("test", String.valueOf(reddit.me().about()));

            return null;
        }
    }
}
```

Can you make sure the credentials are correct?

On a sidenote, if you publish this app using a script OAuth2 app, anyone who knows how to find your string resources could access your account. The recommended way to use the reddit API on an Android app is [interactive authentication](https://mattbdean.gitbooks.io/jraw/content/oauth2.html#interactive-authentication).

**Comment by Leskevicius** [comment]
you tested it on 7603b89 build?

**Comment by Leskevicius** [comment]
My app can be found here: https://github.com/Leskevicius/RedditorsDigest

If that is of any help.

**Comment by mattbdean** [comment]
Pulled the `search-activity` branch, added my own credentials. Still can't reproduce. I would highly suggest taking a look [here](https://github.com/mattbdean/JRAW-Android) for proper authentication.

**Comment by Leskevicius** [comment]
Hey Matt. You can close this issue. I was able to make it work (using userless script for credentials). It was due to how I created my app credentials. And thanks for the suggestion, I will look to upgrade.
