### ISSUE TITLE
comment body html entities are escaped

### ISSUE THREAD

**Issue by jachien** [mattbdean/JRAW#225]
Comment bodies are returned with html entities escaped, but I expect the receive the same reddit markdown used to create the comment.

Here's a reddit submission with html entities in both the submission and comments:
https://www.reddit.com/r/shufflescorebottest/comments/7tgdem/html_entity_test/

**Affected versions:** JRAW 1.0.0

**Steps to reproduce:**
```java
public class HtmlEntityBug {
    public static void main(String[] args) {
        Credentials credentials = // ...
        UserAgent userAgent = // ...
        NetworkAdapter adapter = new OkHttpNetworkAdapter(userAgent);
        RedditClient reddit = OAuthHelper.automatic(adapter, credentials);

        RootCommentNode root = reddit.submission("7tgdem").comments();
        root.loadFully(reddit);
        Iterator<CommentNode<PublicContribution<?>>> it = root.walkTree().iterator();
        while (it.hasNext()) {
            CommentNode<PublicContribution<?>> node = it.next();
            PublicContribution comment = node.getSubject();
            System.out.println("id = " + comment.getId());
            System.out.println("body = " + comment.getBody());
        }
    }
}
```

**Expected output:**
```
id = dtc9ngl
body = < > &
```

**Actual output:**
```
id = 7tgdem
body = null
id = dtc9ngl
body = &lt; &gt; &amp;
```

**Comment by jachien** [comment]
As a side question, is the submission itself supposed to be returned by the RootCommentNode iterator?

Also it looks like html entities are escaped for the submission self text for the following:
```java
System.out.println(reddit.submission("7tgdem").inspect().getSelfText());
```

**Comment by mattbdean** [comment]
The fix here is to send `raw_json=1` in the query. Here's the [updated link](https://www.reddit.com/r/shufflescorebottest/comments/7tgdem/html_entity_test/.json?raw_json=1).

Before:

```json
"body": "&lt; &gt; &amp;",
```

After:

```json
"body": "< > &",
```

> As a side question, is the submission itself supposed to be returned by the RootCommentNode iterator?

Yes, but I know the docs say otherwise.

**Comment by jachien** [comment]
Ah, sorry, I was not aware this was coming from reddit. Is there a way for me to add `raw_json=1` to the query in JRAW?

**Comment by mattbdean** [comment]
The query gets created [here](https://github.com/mattbdean/JRAW/blob/master/lib/src/main/kotlin/net/dean/jraw/references/SubmissionReference.kt#L35), if you don't want to send a PR I'll fix it.

**Comment by jachien** [comment]
Hi, I was taking a stab at this but was running into a few problems.

1) I can't get the lib subproject tests to run from the master branch. I created the credentials file and put it in the right place beforehand. Here's what's happening:

```
$ ./gradlew lib:test
...
> Task :lib:junitPlatformTest 
com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $.
Jan 29, 2018 6:39:38 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek' failed to discover tests
java.lang.NoClassDefFoundError: Could not initialize class net.dean.jraw.test.CredentialsUtil
        at net.dean.jraw.test.TestConfig$reddit$2.invoke(TestConfig.kt:16)
        at net.dean.jraw.test.TestConfig$reddit$2.invoke(TestConfig.kt:9)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at net.dean.jraw.test.TestConfig.getReddit(TestConfig.kt)
        at net.dean.jraw.test.integration.SubredditReferenceTest$1.invoke(SubredditReferenceTest.kt:85)
        at net.dean.jraw.test.integration.SubredditReferenceTest$1.invoke(SubredditReferenceTest.kt:19)
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpec(SpekTestEngine.kt:121)
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:68)
        at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)


Test run finished after 8 ms
[         0 containers found      ]
[         0 containers skipped    ]
[         0 containers started    ]
[         0 containers aborted    ]
[         0 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

2) I'd only be adding rawJson parameter support to CommentRequest, but it sounds like this should be supported across all endpoints. Are you okay with support for all other endpoints being considered out of scope for this issue?

**Comment by mattbdean** [comment]
1. Did you create [`credentials.json`](https://github.com/mattbdean/JRAW#contributing)?
2. Feel free to add `raw_json` to anything you feel needs it.

**Comment by jachien** [comment]
Yeah, I followed the contributing notes and ran
`$ ./gradlew :meta:credentials --no-daemon --console plain`
then copied that the output to lib/src/test/resources/credentials.json.

I figured the credentials file itself is not a problem since I'm getting a NoClassDefFoundError rather than some exception about not being able to load it.

**Comment by mattbdean** [comment]
Asking for raw JSON should probably be done in the HttpRequest class as a flag which defaults to true. When `RedditClient.request` encounters this flag, it adds `raw_json=1` to the query like how it adds the Authorization header. This way the functionality is enabled by default, but only if using a RedditClient to execute the request. If a user happened to use the NetworkAdapter directly, that flag won't have any effect.
