### ISSUE TITLE
NullPointerException in EmbeddedMedia

### ISSUE THREAD

**Issue by KirkBushman** [mattbdean/JRAW#227]
I'm upgrading to 1.0.0, and I'm getting:

     java.lang.NullPointerException: Null type
        at net.dean.jraw.models.$AutoValue_EmbeddedMedia.<init>($AutoValue_EmbeddedMedia.java:20)
        at net.dean.jraw.models.AutoValue_EmbeddedMedia.<init>(AutoValue_EmbeddedMedia.java:14)
        at net.dean.jraw.models.AutoValue_EmbeddedMedia$MoshiJsonAdapter.fromJson(AutoValue_EmbeddedMedia.java:56)

It happens when doing this: --> GET https://oauth.reddit.com/r/all/hot?limit=20&sort=hot
with: 
      
       RedditApp.redditClient
                        .subreddit(subreddit)
                        .posts()
                        .sorting(sorting)
                        .timePeriod(timePeriod)
                        .limit(DEFAULT_BATCH_SIZE)
                        .build()

I went back to try to get the json, but it doesn't do it anymore.
It probably had a problem with a certain Submission in particular, which is lower on the listing now.

Thank you in advance.

**Comment by mpivchev** [comment]
The same error started appearing today for some reason

```
private void initDefaultPaginator() {
        paginator = App.getRedditClient().frontPage()
                .sorting(SubredditSort.TOP)
                .timePeriod(TimePeriod.YEAR)
                .limit(SUBMISSIONS_UPDATE_LIMIT)
                .build();
    }

/...
weakFeedFragment.get().submissionList = weakFeedFragment.get().paginator.next(); // This is where it happens
```

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	   at android.os.AsyncTask$3.done(AsyncTask.java:353)
	   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	   at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	   at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	   at java.lang.Thread.run(Thread.java:764)
	Caused by: java.lang.NullPointerException: Null type
	   at net.dean.jraw.models.$AutoValue_EmbeddedMedia.<init>($AutoValue_EmbeddedMedia.java:20)
	   at net.dean.jraw.models.AutoValue_EmbeddedMedia.<init>(AutoValue_EmbeddedMedia.java:14)
	   at net.dean.jraw.models.AutoValue_EmbeddedMedia$MoshiJsonAdapter.fromJson(AutoValue_EmbeddedMedia.java:56)
	   at net.dean.jraw.models.AutoValue_EmbeddedMedia$MoshiJsonAdapter.fromJson(AutoValue_EmbeddedMedia.java:17)
	   at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	   at net.dean.jraw.models.AutoValue_Submission$MoshiJsonAdapter.fromJson(AutoValue_Submission.java:219)
	   at net.dean.jraw.models.AutoValue_Submission$MoshiJsonAdapter.fromJson(AutoValue_Submission.java:30)
	   at net.dean.jraw.models.internal.AutoValue_RedditModelEnvelope$MoshiJsonAdapter.fromJson(AutoValue_RedditModelEnvelope.java:38)
	   at net.dean.jraw.models.internal.AutoValue_RedditModelEnvelope$MoshiJsonAdapter.fromJson(AutoValue_RedditModelEnvelope.java:17)
	   at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	   at net.dean.jraw.databind.RedditModelAdapterFactory$StaticAdapter.fromJson(RedditModelAdapterFactory.kt:112)
	   at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	   at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.readListing(RedditModelAdapterFactory.kt:197)
	   at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.fromJson(RedditModelAdapterFactory.kt:168)
	   at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.fromJson(RedditModelAdapterFactory.kt:154)
	   at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
	   at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
	   at net.dean.jraw.http.HttpResponse.deserializeWith(HttpResponse.kt:49)
	   at net.dean.jraw.pagination.Paginator.next(Paginator.kt:66)
	   at com.github.mpivchev.app.fragments.FeedFragment$UpdateFeedTask.doInBackground(FeedFragment.java:222)
	   at com.github.mpivchev.app.fragments.FeedFragment$UpdateFeedTask.doInBackground(FeedFragment.java:206)
	   at android.os.AsyncTask$2.call(AsyncTask.java:333)
	   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
	   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
	   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
	   at java.lang.Thread.run(Thread.java:764) 
```

**Comment by mattbdean** [comment]
Has to do with the introduction with reddit's video hosting service. Related to #222. Can fix.

**Comment by mpivchev** [comment]
So for now we should just not show use a paginator for anything?

**Comment by mattbdean** [comment]
I am as well. Fortunately for us reddit is usually pretty good about not breaking anything. They didn't technically break anything here, it's just that I had assumed that the `media` key would always have a certain shape.

Here's what it looks like for OEmbed:

```json
"type": "youtube.com",
"oembed": {
  "provider_url": "https://www.youtube.com/",
  "version": "1.0",
  "title": "Teacher Gives Fake Spelling Test as April Fools Prank OFFICIAL",
  "the rest of the stuff": "goes here"
}
```

Now that reddit video has been more widely adopted, we're seeing this more often:

```json
"reddit_video": {
  "fallback_url": "https://v.redd.it/v8dppg5vrse01/DASH_9_6_M",
  "height": 1080,
  "width": 608,
  "the rest of the stuff": "goes here"
}
```

`oembed` has always been nullable, but I didn't anticipate them ever dropping `type` entirely.

**Comment by mattbdean** [comment]
Fixed! To use the patch you can either wait until v1.1.0 or use JitPack:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.mattbdean:JRAW:7077924'
}
```

**Comment by donnadulcinea** [comment]
When it will be released the 1.1.0?
Which way to fix the problem / address the repository with no issue using Maven?
Thanks!

**Comment by Hronom** [comment]
Hello also interested in release, because also got this problem. So what the progress is?

**Comment by Saketme** [comment]
@donnadulcinea @Hronom you can use jitpack.io to get the latest version immediately instead of waiting for the next release.

**Comment by donnadulcinea** [comment]
@Saketme Thank you, for me it is OK to use _jitpack_, but my question was how to address the current repository using **maven**.
I succeeded after few trials, I know this is taken for granted for most of you, but for me was not, so I paste this for whom is interested. Just add: 
```
        <repository>
            <id>jitpack</id>
            <url>https://jitpack.io</url>
        </repository>
```
to the repositories of the pom.xml, and as a dependency.
```
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20160810</version>
        </dependency>
```
That fix the #227. Thanks Matt and all the contributors for your work!

**Comment by mattbdean** [comment]
I know progress is slow right now, but that's because I'm in school for CS and I also have a programming job, so a lot of the times I'm too exhausted to work on this project. I appreciate you all being patient with me. I should have 1.1.0 out within a few weeks once exams are over.

**Comment by Saketme** [comment]
@donnadulcinea Ah, I'm sorry I did not realize you were asking how to pull in jitpack dependencies using maven.

**Comment by Hronom** [comment]
Also for those guys who starts use jitpack, you also need to include original repository to make it compile:

```
    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-thatjavanerd-maven</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/thatjavanerd/maven</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
```
