### ISSUE TITLE
StatefulAuthHelper.onUserChallenge causes java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Zortax** [mattbdean/JRAW#231]
I'm not sure if this is actually an issue or if I'm just doing something wrong...

Sorry for posting code, but I guess it's the easiest way to describe my issue. I wrote the following class that should manage all the reddit api stuff for my application. For the first Login I'm calling authenticateUser() and then completeAuth() with the final redirect URL.

```java
package de.zortax.zreddit.reddit;// Created by leo on 26.02.18

import de.zortax.zreddit.Main;
import net.dean.jraw.RedditClient;
import net.dean.jraw.http.NetworkAdapter;
import net.dean.jraw.http.OkHttpNetworkAdapter;
import net.dean.jraw.http.UserAgent;
import net.dean.jraw.oauth.AccountHelper;
import net.dean.jraw.oauth.Credentials;
import net.dean.jraw.oauth.StatefulAuthHelper;

import java.util.UUID;

public class RedditManager {

    private RedditState state;

    private UserAgent userAgent;
    private NetworkAdapter networkAdapter;
    private Credentials credentials;
    private RedditClient reddit;
    private AccountHelper accountHelper;
    private StatefulAuthHelper statefulAuthHelper;

    private String[] scopes = {
            "identity",
            "edit",
            "flair",
            "history",
            "mysubreddits",
            "privatemessages",
            "read",
            "report",
            "save",
            "submit",
            "subscribe",
            "vote",
            "wikiread"
    };

    public RedditManager() {
        state = RedditState.NOT_CONNECTED;
        userAgent = new UserAgent("ZReddit", "de.zortax.zreddit", Main.ZREDDIT_VERSION, "Zortax_");
        networkAdapter = new OkHttpNetworkAdapter(userAgent);
        credentials = Credentials.installedApp("m8e7-WxZkPBTiQ", "https://zreddit.zortax.de");
        accountHelper = new AccountHelper(networkAdapter, credentials, Main.getConfig(), UUID.fromString(Main.getConfig().deviceID));
        if (Main.getConfig().accounts.isEmpty() || !Main.getConfig().accounts.containsKey(Main.getConfig().lastAccount))
            reddit = accountHelper.switchToUserless();
        else {
            reddit = accountHelper.trySwitchToUser(Main.getConfig().lastAccount);
            if (reddit == null)
                reddit = accountHelper.switchToUserless();
            else
                state = RedditState.CONNECTED;
        }
    }

    public String authenticateUser() {
        statefulAuthHelper = accountHelper.switchToNewUser();
        String url = statefulAuthHelper.getAuthorizationUrl(true, true, scopes);
        state = RedditState.WAITING_FOR_AUTH;
        return url;
    }

    public boolean isFinalUrl(String url) {
        return statefulAuthHelper.isFinalRedirectUrl(url);
    }

    public void completeAuth(String finalUrl) {
        System.out.println(finalUrl);
        reddit = statefulAuthHelper.onUserChallenge(finalUrl);
        state = RedditState.CONNECTED;
        Main.getConfig().save();
    }

    public RedditClient getReddit() {
        return reddit;
    }

    public RedditState getState() {
        return state;
    }

}

```

Using this class causes the following exception and I really don't understand what the issue is... 

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.dean.jraw.http.BasicAuthenticator.authenticate, parameter route
	at net.dean.jraw.http.BasicAuthenticator.authenticate(BasicAuthenticator.kt)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:288)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:158)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at net.dean.jraw.http.OkHttpNetworkAdapter.execute(OkHttpNetworkAdapter.kt:16)
	at net.dean.jraw.oauth.StatefulAuthHelper.onUserChallenge(StatefulAuthHelper.kt:119)
	at de.zortax.zreddit.reddit.RedditManager.completeAuth(RedditManager.java:73)
```

**Comment by Zortax** [comment]
```
statefulAuthHelper.onUserChallenge(finalUrl);
```
In completeAuth()

**Comment by Zortax** [comment]
When I call completeAuth (or statefulAuthHelper.onUserChallenge) a second time after it threw the exceptions it seems to work... Anyway if this is the correct way to use AccountHelper (and so on) this seems to be an issue of your library...

Also, I forgot to mention that I'm using a build from jitpack (2aa33f4d83) and not the latest release, sorry for that :/

**Comment by mattbdean** [comment]
Sorry for the long turnaround. It turns out that I had the `route` parameter in `BasicAuthenticator.authenticate` marked as non-null and OkHttp passed a null value for it, which is why Kotlin was throwing a tantrum.
