### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: Null type

### ISSUE THREAD

**Issue by andrasferenczi** [mattbdean/JRAW#233]
Hi guys!

I am encountering this NPE:

>[9 ->] GET https://oauth.reddit.com/r/progresspics/new?limit=100&sort=new&after=t3_7w0n0l
[<- 9] 200 application/json: '{"kind": "Listing", "data": {"after": "t3_7v3lbe", "dist": 100, "modhash": null, "whitelist_status": "all_ads", "children": [{"kind": "t3", "data": {"domain": "i.red(...)

```
Exception in thread "main" java.lang.NullPointerException: Null type
	at net.dean.jraw.models.$AutoValue_EmbeddedMedia.<init>($AutoValue_EmbeddedMedia.java:20)
	at net.dean.jraw.models.AutoValue_EmbeddedMedia.<init>(AutoValue_EmbeddedMedia.java:14)
	at net.dean.jraw.models.AutoValue_EmbeddedMedia$MoshiJsonAdapter.fromJson(AutoValue_EmbeddedMedia.java:56)
	at net.dean.jraw.models.AutoValue_EmbeddedMedia$MoshiJsonAdapter.fromJson(AutoValue_EmbeddedMedia.java:17)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at net.dean.jraw.models.AutoValue_Submission$MoshiJsonAdapter.fromJson(AutoValue_Submission.java:219)
	at net.dean.jraw.models.AutoValue_Submission$MoshiJsonAdapter.fromJson(AutoValue_Submission.java:30)
	at net.dean.jraw.models.internal.AutoValue_RedditModelEnvelope$MoshiJsonAdapter.fromJson(AutoValue_RedditModelEnvelope.java:38)
	at net.dean.jraw.models.internal.AutoValue_RedditModelEnvelope$MoshiJsonAdapter.fromJson(AutoValue_RedditModelEnvelope.java:17)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at net.dean.jraw.databind.RedditModelAdapterFactory$StaticAdapter.fromJson(RedditModelAdapterFactory.kt:112)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.readListing(RedditModelAdapterFactory.kt:197)
	at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.fromJson(RedditModelAdapterFactory.kt:168)
	at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.fromJson(RedditModelAdapterFactory.kt:154)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
	at net.dean.jraw.http.HttpResponse.deserializeWith(HttpResponse.kt:49)
	at net.dean.jraw.pagination.Paginator.next(Paginator.kt:65)
	at net.dean.jraw.pagination.Paginator$iterator$1.next(Paginator.kt:79)
	at net.dean.jraw.pagination.Paginator$iterator$1.next(Paginator.kt:77)
	at EntryKt.main(entry.kt:33)
```

This is with JRAW version 1.0.0 . Reddit client is created based on the gitbook.

Relevant code :

    val sub = BotUser
            .redditClient
            .subreddit("progresspics")
            .posts()
            .limit(Paginator.RECOMMENDED_MAX_LIMIT)
            .sorting(SubredditSort.NEW)
            .build()

    val elems: Iterator<Listing<Submission>> = sub.iterator()
    for (elem in elems) {
        println("DONE")
    }
`

I did not see this issue documented, sorry if it is.

Can you help me out with this issue?
Thank you in advance.

**Comment by mattbdean** [comment]
Probably a duplicate of #227

**Comment by andrasferenczi** [comment]
Yes, you are right, it is a duplicate of that. Thanks for the link.
