### ISSUE TITLE
Get replies to a private message

### ISSUE THREAD

**Issue by saket** [mattbdean/JRAW#256]
Now that there's no way to access the underlying json of models, there's no way to find the replies of a private message. I'd like to contribute on this, I just need to know where to start. The JSON looks somewhat like this:

```json
"replies": {
    "kind": "Listing",
    "data": {
      "modhash": "l7r71utosq11406f8dea0de0f991df30083ecb2626b5f3c611",
      "dist": null,
      "children": [
        {
          "kind": "t4",
          "data": {
            "first_message": 715748886,
            "first_message_name": "t4_bu4zdi",
            "subreddit": null,
            "likes": null,
            "replies": "",
            "id": "bu6ld5",
            "subject": "XXX",
            "was_comment": false,
            "score": 0,
            "author": "Saketme",
            "num_comments": null,
            "parent_id": "t4_bu6ld5",
            "subreddit_name_prefixed": null,
            "new": false,
            "body": "XXX",
            "dest": "GandalfTheBlake",
            "body_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;XXX&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "name": "t4_bu6ld5",
            "created": 1526414856,
            "created_utc": 1526386056,
            "context": "",
            "distinguished": null
          }
        },
        {
          "kind": "t4",
          "data": {
            "first_message": 715748886,
            "first_message_name": "t4_bu4zdi",
            "subreddit": null,
            "likes": null,
            "replies": "",
            "id": "buewqx",
            "subject": "XXX",
            "was_comment": false,
            "score": 0,
            "author": "GandalfTheBlake",
            "num_comments": null,
            "parent_id": "t4_bu6ld5",
            "subreddit_name_prefixed": null,
            "new": false,
            "body": "XXX",
            "dest": "Saketme",
            "body_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;XXX&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
            "name": "t4_buewqx",
            "created": 1526456260,
            "created_utc": 1526427460,
            "context": "",
            "distinguished": null
          }
        }
      ],
      "after": null,
      "before": null
    }
},
```

All replies are sent in one go. There's no pagination. Will adding a `Listing<Message>` be sufficient?

**Comment by saket** [comment]
No, I have never seen them to have any nested replies. I am testing this in my branch: https://github.com/saket/JRAW/commits/sn/custom-changes-kt

I'll update my commit to include `@Enveloped`. I quickly skimmed through `RepliesAdapterFactory` and it seems like it only works for comments. Should I add another factory for message replies or make it work with both?

**Comment by saket** [comment]
So I'm seeing this error:

```
E/InboxFolder: Unknown error while refreshing messages in PRIVATE_MESSAGES folder.
    java.lang.IllegalArgumentException: No registered kind for Class 'class net.dean.jraw.models.AutoValue_Message'
        at net.dean.jraw.databind.RedditModelAdapterFactory$StaticAdapter.toJson(RedditModelAdapterFactory.kt:107)
        at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
        at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.writeListing(RedditModelAdapterFactory.kt:232)
        at net.dean.jraw.databind.RedditModelAdapterFactory$ListingAdapter.toJson(RedditModelAdapterFactory.kt:221)
```

Here's how the field is declared:

    @Nullable
    @Enveloped
    @Json(name = "replies")
    public abstract Listing<Message> getReplies();

This doesn't look any different from how `Comment` declares its replies. Is this also related to #237?

**Comment by mattbdean** [comment]
Is that the full stack trace? Are you using `JrawUtils.moshi`?

**Comment by saket** [comment]
No, I removed the full stacktrace. I think I know why this is happening. The adapter generated by AutoValue does an equality check on type it implements:

```java
public final class AutoValueMoshi_ModelAdapterFactory extends ModelAdapterFactory {
@Override
public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, Moshi moshi) {
  ...
  if (type.equals(Message.class)) {
    return Message.jsonAdapter(moshi);
  }
  ...
}
```

So it will only recognize `Message` and not `AutoValue_Message`. It'd be nice if `auto-value-moshi` was using `isAssignableFrom()` instead.

**Comment by mattbdean** [comment]
Fixed with [this commit](https://github.com/mattbdean/JRAW/commit/20323a7acde50ab404df4763d93bc25e9c7b58d8)
